"use client";
import { useState } from "react";
import { Node, Edge } from "@xyflow/react";
import { Button } from "@/components/ui/button";
import { Code, Copy, Check, ChevronDown, ChevronUp } from "lucide-react";

interface TerraformPreviewProps {
  nodes: Node[];
  edges: Edge[];
}

export default function TerraformPreview({ nodes, edges }: TerraformPreviewProps) {
  const [collapsed, setCollapsed] = useState(false);
  const [copied, setCopied] = useState(false);

  const terraformCode = generateTerraform(nodes);

  const handleCopy = () => {
    navigator.clipboard.writeText(terraformCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (nodes.length === 0) return null;

  return (
    <div className="border-t mt-4 pt-4">
      <div className="flex items-center justify-between mb-2">
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="flex items-center gap-1 text-sm font-medium hover:text-primary transition-colors"
        >
          <Code className="h-4 w-4" />
          Terraform Preview
          {collapsed ? <ChevronDown className="h-3 w-3" /> : <ChevronUp className="h-3 w-3" />}
        </button>
        {!collapsed && (
          <Button variant="ghost" size="sm" onClick={handleCopy} className="h-7 px-2">
            {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
          </Button>
        )}
      </div>

      {!collapsed && (
        <pre className="bg-muted/50 border rounded-md p-3 text-xs overflow-auto max-h-64 font-mono whitespace-pre-wrap">
          {terraformCode}
        </pre>
      )}
    </div>
  );
}

function generateTerraform(nodes: Node[]): string {
  if (nodes.length === 0) return "# Add services to see Terraform preview";

  let code = '# Generated by CloudCanva\n\nprovider "aws" {\n  region = "us-east-1"\n}\n\n';

  nodes.forEach((node) => {
    const label = node.data.label;
    const props = node.data.properties || {};
    const name = props.name || node.data.serviceName || label.toLowerCase();
    const safeName = name.replace(/[^a-zA-Z0-9_-]/g, "_").toLowerCase();

    switch (label) {
      case "VPC":
        code += `resource "aws_vpc" "${safeName}" {\n`;
        code += `  cidr_block           = "${props.cidr_block || "10.0.0.0/16"}"\n`;
        code += `  enable_dns_support   = ${props.enable_dns_support ?? true}\n`;
        code += `  enable_dns_hostnames = ${props.enable_dns_hostname ?? true}\n`;
        if (props.tags && Object.keys(props.tags).length > 0) {
          code += `  tags = {\n`;
          Object.entries(props.tags).forEach(([k, v]) => {
            code += `    ${k} = "${v}"\n`;
          });
          code += `  }\n`;
        }
        code += `}\n\n`;
        break;

      case "Subnet":
        code += `resource "aws_subnet" "${safeName}" {\n`;
        if (props.refs?.vpc) code += `  vpc_id                  = aws_vpc.${props.refs.vpc}.id\n`;
        code += `  cidr_block              = "${props.cidr_block || "10.0.1.0/24"}"\n`;
        if (props.availability_zone) code += `  availability_zone       = "${props.availability_zone}"\n`;
        code += `  map_public_ip_on_launch = ${props.map_public_ip_on_launch ?? false}\n`;
        code += `}\n\n`;
        break;

      case "EC2":
        code += `resource "aws_instance" "${safeName}" {\n`;
        code += `  ami           = "${props.ami || "ami-0c55b159cbfafe1f0"}"\n`;
        code += `  instance_type = "${props.instance_type || "t3.micro"}"\n`;
        if (props.refs?.subnet) code += `  subnet_id     = aws_subnet.${props.refs.subnet}.id\n`;
        if (props.refs?.securityGroup) code += `  vpc_security_group_ids = [aws_security_group.${props.refs.securityGroup}.id]\n`;
        if (props.tags && Object.keys(props.tags).length > 0) {
          code += `  tags = {\n`;
          Object.entries(props.tags).forEach(([k, v]) => {
            code += `    ${k} = "${v}"\n`;
          });
          code += `  }\n`;
        }
        code += `}\n\n`;
        break;

      case "S3":
        code += `resource "aws_s3_bucket" "${safeName}" {\n`;
        code += `  bucket = "${props.bucket || safeName}"\n`;
        code += `}\n\n`;
        break;

      case "RDS":
        code += `resource "aws_db_instance" "${safeName}" {\n`;
        code += `  engine               = "${props.engine || "postgresql"}"\n`;
        code += `  instance_class       = "${props.instance_class || "db.t3.micro"}"\n`;
        code += `  allocated_storage    = ${props.allocated_storage || 20}\n`;
        code += `  skip_final_snapshot  = true\n`;
        code += `}\n\n`;
        break;

      case "SecurityGroup":
        code += `resource "aws_security_group" "${safeName}" {\n`;
        if (props.refs?.vpc) code += `  vpc_id      = aws_vpc.${props.refs.vpc}.id\n`;
        if (props.description) code += `  description = "${props.description}"\n`;
        code += `}\n\n`;
        break;

      case "InternetGateway":
        code += `resource "aws_internet_gateway" "${safeName}" {\n`;
        if (props.refs?.vpc) code += `  vpc_id = aws_vpc.${props.refs.vpc}.id\n`;
        code += `}\n\n`;
        break;

      case "ElasticIP":
        code += `resource "aws_eip" "${safeName}" {\n`;
        code += `  domain = "vpc"\n`;
        code += `}\n\n`;
        break;

      case "RouteTable":
        code += `resource "aws_route_table" "${safeName}" {\n`;
        if (props.refs?.vpc) code += `  vpc_id = aws_vpc.${props.refs.vpc}.id\n`;
        code += `}\n\n`;
        break;

      case "LoadBalancer":
        code += `resource "aws_lb" "${safeName}" {\n`;
        code += `  name               = "${props.name || safeName}"\n`;
        code += `  load_balancer_type = "${props.load_balancer_type || "application"}"\n`;
        code += `  internal           = ${props.internal ?? false}\n`;
        code += `}\n\n`;
        break;

      case "TargetGroup":
        code += `resource "aws_lb_target_group" "${safeName}" {\n`;
        code += `  name     = "${props.name || safeName}"\n`;
        code += `  port     = ${props.port || 80}\n`;
        code += `  protocol = "${props.protocol || "HTTP"}"\n`;
        code += `}\n\n`;
        break;

      default:
        code += `# ${label} - ${safeName}\n\n`;
    }
  });

  return code;
}
